auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: loo128's blog
url: http://loo128.github.io
feed: /atom.xml
author_info: <a href="http://loo128.github.io/">Joshua</a>

host: 127.0.0.1
port: 4001