title:            Luz
url:              http://luz.me
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-21332781-7
timezone:         China
paginate: 5
links: 
  - name:         About
    url:          /about